In [4]:
import tensorflow as tf
import numpy as np

In [9]:
cate_list = np.random.randint(63001, size=63001)

In [11]:
cate_list.shape

(63001,)

In [12]:
cate_list = tf.convert_to_tensor(cate_list, dtype=tf.int64)


In [17]:
hist_i = np.random.randint(0,63001,(2,44))

In [32]:
hist_i

array([[24369, 42092, 55427,  9403,  7089, 41531,  8940, 13531, 55051,
        17657, 30677, 12485, 23395, 59476, 49419, 16928, 17025, 10240,
        26910, 55947, 57241,  4524, 21590, 24743, 35405, 35277,  2514,
        35945, 28628, 38644, 16689, 28897, 52875, 62639,  5463,  4954,
        25552, 36529, 54318, 47673, 30447, 55970, 24839,  6779],
       [59044,  7100,  7997, 36127, 51371, 37730, 41817,  8113, 36508,
        11836, 55868, 62429, 21267, 36383, 47922, 29580, 55639, 11159,
        28530, 21127, 19290,  1768,  4128, 26158, 10903, 59833,  1224,
        40011, 58986, 15580, 43397, 35821, 21692, 25601, 55447, 17938,
        36575,  9972, 54443, 21376, 24095, 11927, 57263, 41857]])

In [33]:
hist_i[0, 5:]=0

In [34]:
hist_i

array([[24369, 42092, 55427,  9403,  7089,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0],
       [59044,  7100,  7997, 36127, 51371, 37730, 41817,  8113, 36508,
        11836, 55868, 62429, 21267, 36383, 47922, 29580, 55639, 11159,
        28530, 21127, 19290,  1768,  4128, 26158, 10903, 59833,  1224,
        40011, 58986, 15580, 43397, 35821, 21692, 25601, 55447, 17938,
        36575,  9972, 54443, 21376, 24095, 11927, 57263, 41857]])

In [35]:
tmp = tf.gather(cate_list, hist_i)

In [39]:
tmp_double_mul = tmp * tmp

In [40]:
with tf.Session() as sess:
    tmp_i = sess.run(tmp)
    tmp_double_mul_v = sess.run(tmp_double_mul)

In [43]:
tmp_double_mul_v

array([[3685946944, 2604265024,  911738025, 2043040000, 1054690576,
        2054174329, 2054174329, 2054174329, 2054174329, 2054174329,
        2054174329, 2054174329, 2054174329, 2054174329, 2054174329,
        2054174329, 2054174329, 2054174329, 2054174329, 2054174329,
        2054174329, 2054174329, 2054174329, 2054174329, 2054174329,
        2054174329, 2054174329, 2054174329, 2054174329, 2054174329,
        2054174329, 2054174329, 2054174329, 2054174329, 2054174329,
        2054174329, 2054174329, 2054174329, 2054174329, 2054174329,
        2054174329, 2054174329, 2054174329, 2054174329],
       [2300257521,  498584241,   16152361, 2810272144,  181413961,
        3238406649, 1001532609,    2085136,  923795236,  145467721,
        3111296841, 3607804225,   62299449,    8294400, 3307860196,
          59783824, 3452972644, 2057711044,  381655296,  967521025,
        2488313689,  142396489,  371101696,  539400625,     364816,
        3558361104,  444450724,  621106084,    1822500, 356

In [37]:
tmp_i.shape

(2, 44)

In [38]:
tmp_i

array([[60712, 51032, 30195, 45200, 32476, 45323, 45323, 45323, 45323,
        45323, 45323, 45323, 45323, 45323, 45323, 45323, 45323, 45323,
        45323, 45323, 45323, 45323, 45323, 45323, 45323, 45323, 45323,
        45323, 45323, 45323, 45323, 45323, 45323, 45323, 45323, 45323,
        45323, 45323, 45323, 45323, 45323, 45323, 45323, 45323],
       [47961, 22329,  4019, 53012, 13469, 56907, 31647,  1444, 30394,
        12061, 55779, 60065,  7893,  2880, 57514,  7732, 58762, 45362,
        19536, 31105, 49883, 11933, 19264, 23225,   604, 59652, 21082,
        24922,  1350, 59725, 14167, 30189, 23687, 23765, 61102, 12229,
        14465, 13271,  3440, 50180,  3487,  6953, 22748,  4425]])

In [28]:
with tf.Session() as sess:
    cate_list_i = sess.run(cate_list)

In [31]:
cate_list_i[41857]

4425

In [46]:
lenght = [[2,2,4],[3,4,5]]
mask_data = tf.sequence_mask(lengths=lenght)
# 输出
mask_data


<tf.Tensor 'SequenceMask_2/Less:0' shape=(2, 3, 5) dtype=bool>

In [48]:
with tf.Session() as sess:
    mask_data_v = sess.run(mask_data)
    print(mask_data_v, mask_data_v.shape)

[[[ True  True False False False]
  [ True  True False False False]
  [ True  True  True  True False]]

 [[ True  True  True False False]
  [ True  True  True  True False]
  [ True  True  True  True  True]]] (2, 3, 5)


In [50]:
?np.random.randint

In [51]:
outputs = np.random.rand(32, 1, 10)

In [55]:
-2 ** 32 + 1

-4294967295

In [52]:
paddings = tf.ones_like(outputs) * (-2 ** 32 + 1)


In [54]:
with tf.Session() as sess:
    paddings_v = sess.run(paddings)
    print(paddings_v, paddings_v.shape)

[[[-4.2949673e+09 -4.2949673e+09 -4.2949673e+09 -4.2949673e+09
   -4.2949673e+09 -4.2949673e+09 -4.2949673e+09 -4.2949673e+09
   -4.2949673e+09 -4.2949673e+09]]

 [[-4.2949673e+09 -4.2949673e+09 -4.2949673e+09 -4.2949673e+09
   -4.2949673e+09 -4.2949673e+09 -4.2949673e+09 -4.2949673e+09
   -4.2949673e+09 -4.2949673e+09]]

 [[-4.2949673e+09 -4.2949673e+09 -4.2949673e+09 -4.2949673e+09
   -4.2949673e+09 -4.2949673e+09 -4.2949673e+09 -4.2949673e+09
   -4.2949673e+09 -4.2949673e+09]]

 [[-4.2949673e+09 -4.2949673e+09 -4.2949673e+09 -4.2949673e+09
   -4.2949673e+09 -4.2949673e+09 -4.2949673e+09 -4.2949673e+09
   -4.2949673e+09 -4.2949673e+09]]

 [[-4.2949673e+09 -4.2949673e+09 -4.2949673e+09 -4.2949673e+09
   -4.2949673e+09 -4.2949673e+09 -4.2949673e+09 -4.2949673e+09
   -4.2949673e+09 -4.2949673e+09]]

 [[-4.2949673e+09 -4.2949673e+09 -4.2949673e+09 -4.2949673e+09
   -4.2949673e+09 -4.2949673e+09 -4.2949673e+09 -4.2949673e+09
   -4.2949673e+09 -4.2949673e+09]]

 [[-4.2949673e+09 -4.2949673